### ISSUE TITLE
NullPointerException on DefaultGetTypes.java:42

### ISSUE THREAD

**Issue by MariFio** [highsource/hyperjaxb3#29]
Hi all, hi Lexicon,
I am here because on stackoverflow they're closing my post. 
As said, this is the stack I am now having as an error (the complete one).
Some suggestions?

Unfortunately, I can't share xsds.

`[INFO] Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@366558a2: display name [org.springframework.context.support.FileSystemXmlApplicationContext@366558a2]; startup date [Thu Jul 14 10:59:31 CEST 2016]; root of context hierarchy
[INFO] Loading XML bean definitions from URL [jar:file:/home/sector/.m2/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.1/hyperjaxb3-ejb-plugin-0.6.1.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]
[INFO] Bean factory for application context [org.springframework.context.support.FileSystemXmlApplicationContext@366558a2]: org.springframework.beans.factory.support.DefaultListableBeanFactory@1100757a
[INFO] Bean 'org.springframework.beans.factory.annotation.RequiredAnnotationBeanPostProcessor' is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1100757a: defining beans [ignoring,naming,customizing,embeddableAttributesMapping,mapping,createXAnnotations,annotateOutline,org.springframework.beans.factory.annotation.RequiredAnnotationBeanPostProcessor,wrapSingleBuiltinNonReference,wrapSingleEnumNonReference,wrapSingleHeteroElement,wrapCollectionBuiltinElement,wrapCollectionEnumElement,wrapCollectionEnumAttribute,wrapCollectionBuiltinAttribute,wrapCollectionBuiltinValue,wrapCollectionEnumValue,wrapSingleBuiltinReference,wrapSingleEnumElementReference,wrapSingleClassElementReference,wrapSingleSubstitutedElementReference,wrapSingleWildcardReference,wrapSingleHeteroReference,wrapCollectionHeteroReference,wrapCollectionWildcardReference,wrapCollectionHeteroElement,adaptBuiltinTypeUse,processModel,getTypes,processClassInfo,processPropertyInfos,createIdClass,createDefaultIdPropertyInfos,createDefaultVersionPropertyInfos,getIdPropertyInfos,getVersionPropertyInfos,reservedNames,customizationsContext,abstractCustomizationsUnmarshalledResource,persistenceFactory,persistenceMarshaller,annotationsProcessor,marshalMappings,mappingFilesProcessor,annotations,mappingFiles]; root of factory hierarchy
[INFO] Loading properties file from URL [jar:file:/home/sector/.m2/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.1/hyperjaxb3-ejb-plugin-0.6.1.jar!/org/jvnet/hyperjaxb3/ejb/strategy/naming/impl/ReservedNames.properties]
java.lang.NullPointerException
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.ref(DefaultGetTypes.java:42)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:29)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:25)
	at org.jvnet.hyperjaxb3.ejb.strategy.ignoring.impl.DefaultIgnoring.isPropertyInfoIgnored(DefaultIgnoring.java:175)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:96)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:28)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:17)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:12)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:51)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:32)
	at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:43)
	at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:16)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.run(EjbPlugin.java:213)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:52)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Error while generating code.Location [].
org.xml.sax.SAXParseException; Error during plugin execution.
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:54)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.ref(DefaultGetTypes.java:42)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:29)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:25)
	at org.jvnet.hyperjaxb3.ejb.strategy.ignoring.impl.DefaultIgnoring.isPropertyInfoIgnored(DefaultIgnoring.java:175)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:96)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:28)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:17)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:12)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:51)
	at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:32)
	at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:43)
	at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:16)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.run(EjbPlugin.java:213)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:52)
	... 28 more`

**Comment by highsource** [comment]
Sorry, I can't provide pro bono support for closed source projects.

**Comment by MariFio** [comment]
Ok Lexicon, thanks! I can understand you.. ;-)

**Comment by highsource** [comment]
Consider reducing your schema to the minimum which still reproduces this and the anonymizing it a bit.

**Comment by MariFio** [comment]
Ok perfect, I am going to have a try ;-) Keep you updated, and many thanks again!

**Comment by MariFio** [comment]
This problem was related to the fact that inherited xml type were inheriting properties like uid, id.
I've modified the inheritance strategy so to remove such fields, and now seems to compile (I have other errors but not related to this one).
