### ISSUE TITLE
Support for jaxb2-basics version 0.11

### ISSUE THREAD

**Issue by bgedik** [highsource/hyperjaxb3#44]
It looks like `hyperjaxb3` supports up to version 0.10 of `jaxb2-basics`. That is specified in the top-level pom file. Using it with 0.11 causes problems as below. Is it possible to support 0.11 series? 

``
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/<SOME_PATH_HERE>/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.1/hyperjaxb3-ejb-plugin-0.6.1.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: java.lang.NoSuchFieldError: INSTANCE
``

**Comment by bgedik** [comment]
@highsource Would you be open to contributions regarding this? We are planning to have one of our colleagues take a look at this. Do you envision any difficulties regarding bumping up the jabx2-basics version?

**Comment by highsource** [comment]
> Would you be open to contributions regarding this?

Yes, sure. Better go up to 0.12.0 or even soon-to-be released 0.13.0. Due to Java 9 support.

> Do you envision any difficulties regarding bumping up the jabx2-basics version?

0.11 should not be that much of a problem. However, what we'd really need to do is to upgrade to JAXB 2.3.x to support Java 9+. This will require update to JAXB2-Basics 0.12.0+. I think updates of JAXB2-Basics version per se shoud be non-problematic.
JAXB 2.3.x/Java 9 upgrade can cause problems, it took me a lot of time for `maven-jaxb2-plugin` and JAXB2 Basics.

**Comment by highsource** [comment]
@bgedik Please post the full exception stack trace.

Also would be good if you'd share a MCVE project via PR somewhere under https://github.com/highsource/hyperjaxb3-support (under some `<p>/<projectname>`).

**Comment by bgedik** [comment]
@highsource Here is the full stack trace

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ignoring' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Cannot resolve reference to bean 'customizing' while setting bean property 'customizing'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.jvnet.hyperjaxb3.ejb.strategy.customizing.impl.DefaultCustomizing.<clinit>(DefaultCustomizing.java:1115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:85)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:752)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:717)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:386)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:267)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:857)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:291)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:352)
	at org.jvnet.jaxb2_commons.plugin.spring.AbstractSpringConfigurablePlugin.beforeRun(AbstractSpringConfigurablePlugin.java:66)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.beforeRun(EjbPlugin.java:406)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:51)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:473)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.jvnet.hyperjaxb3.ejb.strategy.customizing.impl.DefaultCustomizing.<clinit>(DefaultCustomizing.java:1115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:85)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:752)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:717)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:386)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:267)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:857)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:291)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:352)
	at org.jvnet.jaxb2_commons.plugin.spring.AbstractSpringConfigurablePlugin.beforeRun(AbstractSpringConfigurablePlugin.java:66)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.beforeRun(EjbPlugin.java:406)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:51)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:473)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Error loading applicaion context from [{classpath*:org/jvnet/hyperjaxb3/ejb/jpa2/plugin/applicationContext.xml,classpath*:org/jvnet/hyperjaxb3/ejb/jpa2/plugin/custom/applicationContext.xml}].
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ignoring' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Cannot resolve reference to bean 'customizing' while setting bean property 'customizing'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.jvnet.hyperjaxb3.ejb.strategy.customizing.impl.DefaultCustomizing.<clinit>(DefaultCustomizing.java:1115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:85)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:752)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:717)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:386)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:267)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:857)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:291)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:352)
	at org.jvnet.jaxb2_commons.plugin.spring.AbstractSpringConfigurablePlugin.beforeRun(AbstractSpringConfigurablePlugin.java:66)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.beforeRun(EjbPlugin.java:406)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:51)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:473)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Error while generating code.Location [].
org.xml.sax.SAXParseException; Error during plugin execution.
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:54)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:473)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.tools.xjc.BadCommandLineException: Error loading  applicaion context from [{classpath*:org/jvnet/hyperjaxb3/ejb/jpa2/plugin/applicationContext.xml,classpath*:org/jvnet/hyperjaxb3/ejb/jpa2/plugin/custom/applicationContext.xml}].
	at org.jvnet.jaxb2_commons.plugin.spring.AbstractSpringConfigurablePlugin.beforeRun(AbstractSpringConfigurablePlugin.java:76)
	at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.beforeRun(EjbPlugin.java:406)
	at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:51)
	... 19 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ignoring' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Cannot resolve reference to bean 'customizing' while setting bean property 'customizing'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:275)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:857)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:291)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:352)
	at org.jvnet.jaxb2_commons.plugin.spring.AbstractSpringConfigurablePlugin.beforeRun(AbstractSpringConfigurablePlugin.java:66)
	... 21 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customizing' defined in URL [jar:file:/home/bgedik/unscrambl/drive/2.1.0/ub16/build/maven/repository/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-plugin/0.6.2/hyperjaxb3-ejb-plugin-0.6.2.jar!/org/jvnet/hyperjaxb3/ejb/plugin/applicationContext.xml]: Instantiation of bean failed; nested exception is java.lang.NoSuchFieldError: INSTANCE
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:451)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:155)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:246)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:160)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:267)
	... 32 more
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.jvnet.hyperjaxb3.ejb.strategy.customizing.impl.DefaultCustomizing.<clinit>(DefaultCustomizing.java:1115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:85)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:752)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:717)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:386)
	... 37 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] drive-parent ....................................... SUCCESS [  0.994 s]
[INFO] drive-src-parent ................................... SUCCESS [  0.045 s]
[INFO] drive-antlr ........................................ SUCCESS [  1.069 s]
[INFO] drive-thrift ....................................... SUCCESS [  1.577 s]
[INFO] drive-jaxb ......................................... FAILURE [  3.373 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.592 s (Wall Clock)
[INFO] Finished at: 2018-06-21T12:21:13-07:00
[INFO] Final Memory: 49M/1323M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.3:generate (jaxb-sources) on project drive-jaxb: Failed to compile input schema(s)! Error messages should have been provided. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :drive-jaxb

**Comment by highsource** [comment]
Thank you very much. Please also consider providing an MCVE project.

**Comment by laurentschoelens** [comment]
Hi @bgedik 

This was adressed when hyperjaxb3 was merged into [jaxb-tools](https://github.com/highsource/jaxb-tools)  repository, which now holds both jaxb-basics and hyperjaxb3.

Using 2.x version of the plugins and hyperjaxb3 should solve your problem.

Please check [migration guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide#migration-from-previous-version-0x--1x-to-v2)
